version: '3.8'

services:
  tariff-service:
    build:
      context: ./tariff-service  # Projenin kök dizini
      dockerfile: src/main/resources/Dockerfile  # Dockerfile'ın yeni yolu
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tariffdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tariffservice
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - parking-network

  tariff-operation-service:
    build:
      context: ./tariff-operation-service  # Projenin kök dizini
      dockerfile: src/main/resources/Dockerfile  # Dockerfile'ın yeni yolu
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tariffdb  # Eğer bu servisin de veritabanı erişimi olacaksa
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tariffoperationservice  # Eğer MongoDB kullanıyorsanız
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Kafka bağlantısı için gerekli
      - TARIFF_SERVICE_URL=http://tariff-service:8080/api/v1/tariffs  # Tariff Service'in URL'si
    networks:
      - parking-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=tariffdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - parking-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - parking-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - parking-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - parking-network

volumes:
  mysql_data:
  mongo_data:

networks:
  parking-network:
